export const getProblems = async (req, res) => {
  try {
  } catch (error) {
    console.log("error in get problems controller", error.message);
  }
};

export const getSingleProblem = async (req, res) => {
  try {
  } catch (error) {
    console.log("error in get single problem controller", error.message);
  }
};
